language: python
python:
  - "2.7"
# command to run tests
install:
  - pip install virtualenv
script:
  - virtualenv venv
  - . ./venv/bin/activate
  - ./setup.py install
  - ./setup.py test
cache:
  directories:
    - venv
