language: python
python:
  - "2.7"
# command to run tests
before_script:
  - ". ./get-z3-from-source.sh || true"
  - "pip install virtualenv nose"
  - cd $TRAVIS_BUILD_DIR
script:
  - nosetests
cache:
  directories:
    - venv
    - z3
