language: python
python:
  - "2.7"
install:
  - "pip install virtualenv"
  - ". ./get-z3-from-source.sh"
# - "pip install -r requirements.txt"
# command to run tests
script: nosetests
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
